# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'graduatR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for graduatR
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'GoogleSignIn'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'Charts'
    pod 'JSQMessagesViewController'

  target 'graduatRTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
